import { useState } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Stack, Box, Button, Center } from "@mantine/core"; //
import Navbar from "@/components/Navbar";
import Broadstats from "@/components/Broadstats";
import DifficultyGrid from "@/components/DifficultyGrid";
import { useRouter } from "next/router";
import { authClient } from "@/lib/auth-client";
import PartnerSearch from "@/components/PartnerSearch";

export default function Home() {
  const router = useRouter(); // Next router used for navigation AKA redirecting page
  const [loading, setLoading] = useState(false); // State to manage loading state of the button
  const [error, setError] = useState<string | null>(null);
  const { data: session } = authClient.useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/apple.png" />
      </Head>
      {/* Stack creates a flex column. 
          h="100vh" ensures the page is at least the height of the screen.
          gap={0} prevents unwanted spacing between the header and the grid.
      */}
      <Stack h="100vh" gap={0}>
        <Navbar
          links={["Time", "Players", "Tournament"]}
          title="Code BattleGrounds"
        />

        {/* Wrapping the grid in a Box with flex: 1 
            forces this section to grow and fill all empty space,
            naturally pushing Broadstats to the bottom.
        */}
        <Box style={{ flex: 1 }}>
          <DifficultyGrid />
        </Box>

        {/* Center the button to create the game room */}
        <Center mb="lg" style={{ flexDirection: "column", gap: 8 }}>
          {error && (
            <div style={{ color: "red", marginBottom: 8 }}>{error}</div>
          )}
          <Box style={{ flex: 1 }}>
            <PartnerSearch />
          </Box>
        </Center>
      </Stack>
    </>
  );
}
