import DifficultyGrid from "@/components/DifficultyGrid";
import Navbar from "@/components/Navbar";
import PartnerSearch from "@/components/PartnerSearch";
import { Box, Stack } from "@mantine/core"; //
import Head from "next/head";

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {/* Stack creates a flex column. 
          h="100vh" ensures the page is at least the height of the screen.
          gap={0} prevents unwanted spacing between the header and the grid.
      */}

      <Box h="100vh">
        <Stack gap={0}>
          <Navbar
            links={["Time", "Players", "Tournament"]}
            title="Code BattleGrounds"
          />

          <Box style={{ flex: 1 }} mt="xl">
            <DifficultyGrid />
          </Box>

          {/* Center the button to create the game room */}

          <Box style={{ flex: 1 }}>
            <PartnerSearch />
          </Box>
        </Stack>
      </Box>
    </>
  );
}
