name: Test Pull Request

on: 
  pull_request:
    branches:
      - main

jobs:
  test-bolt:
    runs-on: ubuntu-latest
    container:
      image: node:20
    defaults:
      run:
        working-directory: ./bolt_slack
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - run: npm install
      - run: npm ci
      - run: npm test -- --passWithNoTests
  test-mongo:
    runs-on: ubuntu-latest
    container:
      image: node:20
    defaults:
      run:
        working-directory: ./mongo_storage
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20  
      - run: npm install
      - run: npm test -- --passWithNoTests
