steps:
  # build the rootjail container image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - build-artifacts/Dockerfile.executor-image
      - -t
      - "us-central1-docker.pkg.dev/code-battlegrounds/app/rootjail:latest"
      - .

  # push rootjail image
  - name: gcr.io/cloud-builders/docker
    args: ["push", "us-central1-docker.pkg.dev/code-battlegrounds/app/rootjail:latest"]

  # this bit builds the full prod image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - build-artifacts/Dockerfile
      - -t
      - "us-central1-docker.pkg.dev/code-battlegrounds/app/app:latest"
      - .

  # push the prod image
  - name: gcr.io/cloud-builders/docker
    args: ["push", "us-central1-docker.pkg.dev/code-battlegrounds/app/app:latest"]

  # build the prisma deployment image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - build-artifacts/Dockerfile.migrate
      - -t
      - "us-central1-docker.pkg.dev/code-battlegrounds/app/migrate:latest"
      - .

  # push deployment image
  - name: gcr.io/cloud-builders/docker
    args: ["push", "us-central1-docker.pkg.dev/code-battlegrounds/app/migrate:latest"]

images:
  - "us-central1-docker.pkg.dev/code-battlegrounds/app/app:latest"
  - "us-central1-docker.pkg.dev/code-battlegrounds/app/migrate:latest"
  - "us-central1-docker.pkg.dev/code-battlegrounds/app/rootjail:latest"
timeout: "1200s" # 20 minutes
