steps:
  # build the rootjail container image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - build-artifacts/Dockerfile.executor-image
      - -t
      - "us-central1-docker.pkg.dev/code-battlegrounds/app/rootjail:latest"
      - .

  # push rootjail image
  - name: gcr.io/cloud-builders/docker
    args: ["push", "us-central1-docker.pkg.dev/code-battlegrounds/app/rootjail:latest"]


images:
      - "us-central1-docker.pkg.dev/code-battlegrounds/app/rootjail:latest"
timeout: "1200s" # 20 minutes